"""Phase 10 — Asset Oracle Catalog & Resolver package.

Public surface:
- ``load_catalog_from_repo`` — load (and validate) the shared manifest at
  ``assets/catalog/catalog.json``, defaulting to the repo-root path derived
  from the package location (same derivation as ``app.core.config.REPO_ROOT``);
- ``resolve`` — deterministic resolution of a raw payload or typed request;
- ``Provenance`` — the resolution-provenance enum (Phase 10 emits
  CATALOG_EXACT / CATALOG_ALIAS / SEMANTIC_MATCH / FALLBACK; the remaining
  values are reserved for Phases 12-15).
"""

from __future__ import annotations

from app.assets.catalog import (
    ASSET_VERSION_MIN,
    CATEGORY_ALLOWLIST,
    COMPOSITE_KIND_ALLOWLIST,
    Catalog,
    CatalogError,
    CatalogValidationError,
    DOCUMENTED_ASSET_KEYS,
    AssetDescriptor,
    Dimensions,
    MATERIAL_VOCABULARY,
    MAX_ALLOWED_ANCHORS,
    MAX_ALIASES,
    MAX_COLORS,
    MAX_CATALOG_STRING_LENGTH,
    MAX_EVIDENCE_CAPABILITIES,
    MAX_SUPPORTED_INTERACTIONS,
    MAX_TAGS,
    MAX_VARIANTS_PER_ASSET,
    MAX_VARIANT_ALLOWLIST,
    OPTIONAL_ASSET_KEYS,
    REQUIRED_ASSET_KEYS,
    RENDER_KIND_ALLOWLIST,
    SCALE_MAX_BOUND,
    SCALE_MIN_BOUND,
    STATE_VOCABULARY,
    TEMPLATE_VOCABULARY,
    VARIANT_PARAM_KINDS,
    VariantParamSpec,
    VariantSpec,
    load_catalog,
    load_catalog_from_repo,
    validate_catalog_data,
)
from app.assets.resolver import (
    SEMANTIC_CATEGORY_WEIGHT,
    SEMANTIC_MIN_CONFIDENCE,
    SEMANTIC_SUBTYPE_WEIGHT,
    SEMANTIC_TAG_WEIGHT,
    AssetRequest,
    AssetResolution,
    AssetResolver,
    AssetVariantError,
    AssetVariantResolution,
    AssetVariantView,
    Provenance,
    apply_variant,
    normalize,
    resolve,
    resolve_placements_provenance,
    resolve_with_variant,
)
from app.assets.validation import (
    FORBIDDEN_URL_TOKENS,
    MAX_ASSET_STRING_LENGTH,
    MAX_CAPABILITIES,
    MAX_STYLE_HINTS,
    MAX_TAGS,
    AssetRequestValidationError,
    validate_asset_request,
)

__all__ = [
    "ASSET_VERSION_MIN",
    "CATEGORY_ALLOWLIST",
    "COMPOSITE_KIND_ALLOWLIST",
    "Catalog",
    "CatalogError",
    "CatalogValidationError",
    "DOCUMENTED_ASSET_KEYS",
    "AssetDescriptor",
    "Dimensions",
    "MATERIAL_VOCABULARY",
    "MAX_ALLOWED_ANCHORS",
    "MAX_ALIASES",
    "MAX_COLORS",
    "MAX_CATALOG_STRING_LENGTH",
    "MAX_EVIDENCE_CAPABILITIES",
    "MAX_SUPPORTED_INTERACTIONS",
    "MAX_TAGS",
    "MAX_VARIANTS_PER_ASSET",
    "MAX_VARIANT_ALLOWLIST",
    "OPTIONAL_ASSET_KEYS",
    "REQUIRED_ASSET_KEYS",
    "RENDER_KIND_ALLOWLIST",
    "SCALE_MAX_BOUND",
    "SCALE_MIN_BOUND",
    "STATE_VOCABULARY",
    "TEMPLATE_VOCABULARY",
    "VARIANT_PARAM_KINDS",
    "VariantParamSpec",
    "VariantSpec",
    "load_catalog",
    "load_catalog_from_repo",
    "validate_catalog_data",
    "SEMANTIC_CATEGORY_WEIGHT",
    "SEMANTIC_MIN_CONFIDENCE",
    "SEMANTIC_SUBTYPE_WEIGHT",
    "SEMANTIC_TAG_WEIGHT",
    "AssetRequest",
    "AssetResolution",
    "AssetResolver",
    "AssetVariantError",
    "AssetVariantResolution",
    "AssetVariantView",
    "Provenance",
    "apply_variant",
    "normalize",
    "resolve",
    "resolve_placements_provenance",
    "resolve_with_variant",
    "FORBIDDEN_URL_TOKENS",
    "MAX_ASSET_STRING_LENGTH",
    "MAX_CAPABILITIES",
    "MAX_STYLE_HINTS",
    "MAX_TAGS",
    "AssetRequestValidationError",
    "validate_asset_request",
]