"""RAD 3 adapter generator: manifest-driven regeneration and drift checks (65A.5/65A.6)."""

import argparse
import fnmatch
import hashlib
import json
import os
import sys
from pathlib import Path

ADAPTERS = ("codex", "opencode", "claude", "cursor")
ADAPTER_DIRS = {"codex": ".codex", "opencode": ".opencode", "claude": ".claude", "cursor": ".cursor"}
ALLOWLISTS = {
    # Real plugin/installer files under .opencode that are NOT generated by us.
    "opencode": ["node_modules/**", "package.json", "package-lock.json", ".gitignore"],
    "codex": [],
    "claude": [],
    "cursor": [],
}

BANNER_HASH = "# GENERATED BY RAD 3 adapter generator \u2014 DO NOT HAND EDIT \u2014 core {fp}"
BANNER_HTML = "<!-- GENERATED BY RAD 3 adapter generator \u2014 DO NOT HAND EDIT \u2014 core {fp} -->"

ROLE_ORDER = ("adversary", "backend-dev", "frontend-dev", "qa")
ROLE_DESCRIPTIONS = {
    "adversary": "Adversarial RAD reviewer. Use after QA/implementation to attack edge cases and record findings without fixing them.",
    "backend-dev": "Backend/domain specialist. Use for domain logic, APIs, persistence, providers and backend/domain tests.",
    "frontend-dev": "Frontend implementation specialist. Use for user-facing/client implementation and frontend unit tests.",
    "qa": "Independent RAD QA. Use after implementation to author/run E2E validation, manage DEFECTS.md and independently retest fixes.",
}
ROLE_EFFORTS = {"adversary": "xhigh", "backend-dev": "high", "frontend-dev": "high", "qa": "high"}

# Manifest workflow keys that map to cursor command files. `phase_gate` intentionally has no command.
CURSOR_COMMANDS = {
    "preflight": "rad-preflight.md",
    "architecture_audit": "rad-audit.md",
    "implementation": "rad-build.md",
    "final_release": "rad-release.md",
    "resume": "rad-resume.md",
}


class GeneratorError(Exception):
    """Manifest/IO/usage fault that must exit with code 2."""


def _banner(fp, html=False):
    return (BANNER_HTML if html else BANNER_HASH).format(fp=fp)


def _encode(lines):
    return ("\r\n".join(lines) + "\r\n").encode("utf-8")


def _blurb(role_path):
    return [
        "This is a generated RAD runtime adapter.",
        "",
        "Before doing any work, read `.rad/core/protocol.md` and `%s`. Read the relevant workflow under `.rad/workflows/` and applicable policies under `.rad/policies/`. Those canonical files are the source of truth. `REQUIREMENTS.md` is immutable. If this adapter conflicts with `.rad/`, follow `.rad/`." % role_path,
    ]


def _role_path(manifest, role):
    """Resolve a role's canonical path from the manifest (ADV-002).

    The manifest is authoritative (65A.6 / 65B.5): `roles[role]["path"]` wins when
    present; fall back to the conventional `.rad/roles/<role>.md` only when the
    role has no manifest entry or no usable `path` key.
    """
    entry = manifest.get("roles", {}).get(role)
    if isinstance(entry, dict):
        path = entry.get("path")
        if isinstance(path, str) and path:
            return path
    return ".rad/roles/%s.md" % role


def _opencode_bash_perms():
    return [
        '  bash:',
        '    "*": ask',
        '    "git status*": allow',
        '    "git diff*": allow',
        '    "git log*": allow',
        '    "git show*": allow',
        '    "python tools/generate_adapters.py --check*": allow',
        '    "python ./tools/generate_adapters.py --check*": allow',
        '    "python3 tools/generate_adapters.py --check*": allow',
        '    "npm test*": allow',
        '    "npm run test*": allow',
        '    "npm run build*": allow',
        '    "npm run lint*": allow',
        '    "npx playwright test*": allow',
    ]


def _opencode_edit_perms(role):
    if role in ("frontend-dev", "backend-dev"):
        return [("*", "allow"), ("REQUIREMENTS.md", "deny"), (".rad/*", "deny"), (".codex/*", "deny"),
                (".opencode/*", "deny"), (".claude/*", "deny"), (".cursor/*", "deny"), ("DEFECTS.md", "deny"),
                ("ADVERSARIAL_REVIEW.md", "deny"), ("e2e/*", "deny")]
    if role == "qa":
        return [("*", "deny"), ("e2e/*", "allow"), ("screenshots/evidence/*", "allow"),
                ("screenshots/generated/*", "allow"), ("DEFECTS.md", "allow"), ("NAMING_AUDIT.md", "allow")]
    return [("*", "deny"), ("ADVERSARIAL_REVIEW.md", "allow"), ("screenshots/evidence/*", "allow"),
            ("screenshots/generated/*", "allow")]


def _codex_config(fp):
    return _encode([
        _banner(fp),
        'model = "gpt-5.6-sol"',
        'model_reasoning_effort = "high"',
        'approval_policy = "on-request"',
        'default_permissions = ":workspace"',
        "",
        "[windows]",
        'sandbox = "elevated"',
        "",
        "[agents]",
        "max_concurrent_threads_per_session = 4",
        'default_subagent_model = "gpt-5.6-sol"',
        'default_subagent_reasoning_effort = "high"',
    ])


def _codex_agent(fp, role, role_path):
    lines = [
        _banner(fp),
        'name = "%s"' % role,
        'description = "%s"' % ROLE_DESCRIPTIONS[role],
        'model = "gpt-5.6-sol"',
        'model_reasoning_effort = "%s"' % ROLE_EFFORTS[role],
        "",
        'developer_instructions = """',
    ]
    lines.extend(_blurb(role_path))
    lines.extend(["", '"""'])
    return _encode(lines)


def _claude_agent(fp, role, role_path):
    lines = ["---", "name: %s" % role, "description: %s" % ROLE_DESCRIPTIONS[role], "model: inherit", "---", ""]
    lines.append(_banner(fp, html=True))
    lines.extend(_blurb(role_path))
    return _encode(lines)


def _cursor_agent(fp, role, role_path):
    lines = ["---", "name: %s" % role, "description: %s" % ROLE_DESCRIPTIONS[role], "---", ""]
    lines.append(_banner(fp, html=True))
    lines.extend(_blurb(role_path))
    return _encode(lines)


def _cursor_command(fp, workflow_path):
    return _encode([
        _banner(fp, html=True),
        "Read `%s` and execute that canonical RAD workflow. Also follow root `AGENTS.md` and `.rad/core/protocol.md`." % workflow_path,
    ])


def _opencode_orchestrator(fp):
    lines = [
        "---",
        "description: RAD delivery lead. Plans, delegates, triages and gates; never writes product code.",
        "mode: primary",
        "permission:",
        "  edit:",
        '    "*": deny',
        '    "DEFECTS.md": allow',
        '    "ADVERSARIAL_REVIEW.md": allow',
        '    "POC_REPORT.md": allow',
        '    "DECISIONS.md": allow',
        '    "NAMING_AUDIT.md": allow',
        '    "docs/adr/*": allow',
    ]
    lines.extend(_opencode_bash_perms())
    lines.extend([
        "---",
        "",
        _banner(fp, html=True),
        "Read `.rad/core/protocol.md` and `.rad/roles/orchestrator.md`. Those files are canonical. Read the relevant `.rad/workflows/` and `.rad/policies/` files before each gate.",
    ])
    return _encode(lines)


def _opencode_subagent(fp, role, role_path):
    lines = [
        "---",
        "description: %s" % ROLE_DESCRIPTIONS[role],
        "mode: subagent",
        "permission:",
        "  edit:",
    ]
    lines.extend('    "%s": %s' % (key, value) for key, value in _opencode_edit_perms(role))
    lines.extend(_opencode_bash_perms())
    lines.extend([
        "---",
        "",
        _banner(fp, html=True),
    ])
    lines.extend(_blurb(role_path))
    return _encode(lines)


def _root_claude(fp):
    return _encode([
        _banner(fp, html=True),
        "@AGENTS.md",
        "",
        "The canonical RAD instructions are under `.rad/`. Treat generated `.claude/` files as adapters only.",
    ])


def _codex_readme(fp):
    return _encode([
        _banner(fp),
        "# Codex adapter",
        "",
        "The main Codex thread is the RAD orchestrator through root `AGENTS.md`.",
        "Delegated roles are generated under `.codex/agents/`.",
    ])


def _claude_readme(fp):
    return _encode([
        _banner(fp),
        "# Claude Code adapter",
        "",
        "Root `CLAUDE.md` imports the shared `AGENTS.md`. Custom delegated roles live in `.claude/agents/`. The main Claude session acts as orchestrator.",
    ])


def _cursor_readme(fp):
    return _encode([
        _banner(fp),
        "# Cursor adapter",
        "",
        "Cursor reads root `AGENTS.md`. Native RAD delegated roles live in `.cursor/agents/`; convenience commands live in `.cursor/commands/`. The main Cursor Agent acts as orchestrator.",
    ])


def _opencode_readme(fp):
    return _encode([
        _banner(fp),
        "# OpenCode adapter",
        "",
        "Select the generated `orchestrator` primary agent. It delegates to the four generated subagents. OpenCode-specific permissions strengthen canonical role ownership while allowing routine local validation commands; package installation/network-sensitive commands still require approval.",
    ])


def _active_adapters(manifest):
    return [a for a in manifest.get("generated_adapters", []) if a in ADAPTERS]


def expected_files(manifest, fp):
    active = _active_adapters(manifest)
    files = {}
    if "claude" in active:
        files["CLAUDE.md"] = _root_claude(fp)
    if "codex" in active:
        files[".codex/config.toml"] = _codex_config(fp)
        files[".codex/README.md"] = _codex_readme(fp)
        for role in ROLE_ORDER:
            files[".codex/agents/%s.toml" % role] = _codex_agent(fp, role, _role_path(manifest, role))
    if "claude" in active:
        files[".claude/README.md"] = _claude_readme(fp)
        for role in ROLE_ORDER:
            files[".claude/agents/%s.md" % role] = _claude_agent(fp, role, _role_path(manifest, role))
    if "cursor" in active:
        files[".cursor/README.md"] = _cursor_readme(fp)
        for role in ROLE_ORDER:
            files[".cursor/agents/%s.md" % role] = _cursor_agent(fp, role, _role_path(manifest, role))
        for key, command in CURSOR_COMMANDS.items():
            if key in manifest["workflows"]:
                files[".cursor/commands/%s" % command] = _cursor_command(fp, manifest["workflows"][key])
    if "opencode" in active:
        files[".opencode/README.md"] = _opencode_readme(fp)
        files[".opencode/agents/orchestrator.md"] = _opencode_orchestrator(fp)
        for role in ROLE_ORDER:
            files[".opencode/agents/%s.md" % role] = _opencode_subagent(fp, role, _role_path(manifest, role))
    return files


def _real_inside(path, base):
    """True when realpath(*path*) is realpath(*base*) or one of its descendants.

    `os.path.realpath` resolves symlinks AND Windows junctions, so a junctioned or
    symlinked adapter directory (or an entry inside one) can never leak external
    files into the stale scan (ADV-005 / 65A.5).
    """
    try:
        base_real = os.path.realpath(str(base))
        path_real = os.path.realpath(str(path))
        common = os.path.commonpath([base_real, path_real])
        return os.path.normcase(common) == os.path.normcase(base_real)
    except ValueError:
        return False


def load_manifest(manifest_path, workspace_root=None):
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise GeneratorError("cannot read manifest %s: %s" % (manifest_path, exc))
    except ValueError as exc:
        raise GeneratorError("invalid JSON in manifest %s: %s" % (manifest_path, exc))
    for key in ("workflows", "roles", "generated_adapters"):
        if key not in manifest:
            raise GeneratorError("manifest %s is missing required key %r" % (manifest_path, key))
    if not isinstance(manifest["workflows"], dict) or not isinstance(manifest["roles"], dict) \
            or not isinstance(manifest["generated_adapters"], list):
        raise GeneratorError("manifest %s has invalid types for required keys" % manifest_path)

    # Element-level validation (ADV-008): malformed members must surface as a clean
    # GeneratorError (exit 2) with a parseable --json report, never a traceback.
    for key in ("core_protocol", "orchestrator_role", "product_contract"):
        if not isinstance(manifest.get(key), str):
            raise GeneratorError("manifest %s: %r must be a string" % (manifest_path, key))
    for role, entry in manifest["roles"].items():
        if not isinstance(entry, dict):
            raise GeneratorError("manifest %s: roles[%r] must be a dict (got %s)"
                                 % (manifest_path, role, type(entry).__name__))
        path = entry.get("path")
        if not isinstance(path, str) or not path:
            raise GeneratorError("manifest %s: roles[%r][\"path\"] must be a non-empty string"
                                 % (manifest_path, role))
    for workflow, value in manifest["workflows"].items():
        if not isinstance(value, str):
            raise GeneratorError("manifest %s: workflows[%r] must be a string (got %s)"
                                 % (manifest_path, workflow, type(value).__name__))
    policies = manifest.get("policies", [])
    if not isinstance(policies, list) or not all(isinstance(p, str) for p in policies):
        raise GeneratorError("manifest %s: policies must be a list of strings" % manifest_path)
    for adapter in manifest["generated_adapters"]:
        if not isinstance(adapter, str):
            raise GeneratorError("manifest %s: generated_adapters must be a list of strings" % manifest_path)

    if workspace_root is None:
        workspace_root = manifest_path.resolve().parent.parent
    _validate_manifest_paths(manifest, workspace_root)
    return manifest


def _validate_manifest_paths(manifest, root):
    """Reject manifest path values that are absolute or escape the workspace (ADV-009).

    These values are fingerprint input and are interpolated into generated adapter
    content, so they must stay workspace-relative and inside the workspace root.
    """
    root = Path(root)
    values = [manifest["core_protocol"], manifest["orchestrator_role"]]
    values += [entry["path"] for entry in manifest["roles"].values()]
    values += list(manifest["workflows"].values())
    values += list(manifest.get("policies", []))
    for value in values:
        p = Path(value)
        if p.is_absolute() or p.root:
            raise GeneratorError(
                "manifest path %r must be workspace-relative (absolute paths are rejected)" % value)
        # Lexical norm first, then realpath containment (same check as ADV-005).
        if not _real_inside(os.path.join(str(root), os.path.normpath(value)), str(root)):
            raise GeneratorError(
                "manifest path %r escapes the workspace root %s" % (value, root))


def core_fingerprint(root, manifest_rel, manifest):
    rels = [manifest_rel, manifest["core_protocol"], manifest["orchestrator_role"]]
    rels.extend(role["path"] for role in manifest["roles"].values())
    rels.extend(manifest["workflows"].values())
    rels.extend(manifest.get("policies", []))
    rels = sorted(set(rels))
    digest = hashlib.sha256()
    for rel in rels:
        # A canonical file referenced by the manifest must exist; treat absence as an integrity error.
        try:
            data = (root / rel).read_bytes()
        except OSError as exc:
            raise GeneratorError("missing canonical file referenced by manifest: %s (%s)" % (rel, exc))
        digest.update(rel.encode("utf-8"))
        digest.update(b"\x00")
        digest.update(data)
        digest.update(b"\x00")
    return digest.hexdigest()[:16]


def _is_allowlisted(rel, allow):
    for item in allow:
        if item.endswith("/**"):
            prefix = item[:-3]
            if rel == prefix or rel.startswith(prefix + "/"):
                return True
        elif fnmatch.fnmatchcase(rel, item):
            return True
    return False


def _scan_stale(root, manifest, expected_rels, notes=None):
    """Report generated files that should no longer exist (65A.5 / 65B.4).

    Scans ALL FOUR adapter roots regardless of activation state: a deactivated
    adapter's generated tree is still compared against the expected set, so
    obsolete files are caught (ADV-001 / DEF-001). The walk is confined to the
    workspace: adapter roots (and each directory/file encountered) whose realpath
    escapes the workspace are skipped, never traversed, never reported (ADV-005).
    """
    stale = []
    active = set(_active_adapters(manifest))
    for adapter in ADAPTERS:
        base = root / ADAPTER_DIRS[adapter]
        if not base.is_dir():
            continue
        if not _real_inside(str(base), str(root)):
            if notes is not None:
                notes.append(
                    "skipped %s: adapter directory resolves outside the workspace (%s)"
                    % (ADAPTER_DIRS[adapter], os.path.realpath(str(base))))
            continue
        allow = ALLOWLISTS[adapter]

        def short_name(rel_dir, name):
            return (rel_dir / name).as_posix() if str(rel_dir) != "." else name

        for dirpath, dirnames, filenames in os.walk(base):
            if not _real_inside(dirpath, str(base)):
                # Unreachable once dirs are pruned below; hard containment guard.
                dirnames[:] = []
                continue
            rel_dir = Path(dirpath).relative_to(base)
            pruned = []
            for d in sorted(dirnames):
                short = short_name(rel_dir, d)
                if _is_allowlisted(short, allow):
                    continue
                if _real_inside(os.path.join(dirpath, d), str(base)):
                    pruned.append(d)
            dirnames[:] = pruned
            for name in sorted(filenames):
                short = short_name(rel_dir, name)
                rel = ADAPTER_DIRS[adapter] + "/" + short
                if rel in expected_rels or _is_allowlisted(short, allow):
                    continue
                if not _real_inside(os.path.join(dirpath, name), str(base)):
                    continue
                stale.append(rel)
    if "claude" not in active and "CLAUDE.md" not in expected_rels:
        # Root CLAUDE.md exists only as a generated file: if claude is deactivated
        # any leftover is stale (ADV-001 / DEF-001).
        if (root / "CLAUDE.md").is_file():
            stale.append("CLAUDE.md")
    return stale


def check(root, manifest, fp):
    expected = expected_files(manifest, fp)
    missing = []
    drifted = []
    for rel, data in expected.items():
        path = root / rel
        if not path.is_file():
            missing.append(rel)
        elif path.read_bytes() != data:
            drifted.append(rel)
    notes = []
    stale = _scan_stale(root, manifest, set(expected), notes)
    return missing, drifted, stale, notes


def _atomic_write_bytes(path, data):
    """Write *data* to *path* atomically: temp file in the same dir, then os.replace.

    Concurrent `--check` can never observe a half-written file (ADV-007).
    """
    tmp = str(path) + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(data)
    os.replace(tmp, str(path))


def write_all(root, manifest, fp):
    expected = expected_files(manifest, fp)
    written = []
    for rel, data in expected.items():
        path = root / rel
        if path.is_file() and path.read_bytes() == data:
            # Up to date: skip the write entirely (no mtime churn, no non-atomic
            # rewrite) so a second `--all` is byte- and metadata-idempotent (ADV-007).
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        _atomic_write_bytes(path, data)
        written.append(rel)
    return written


def main(argv=None):
    parser = argparse.ArgumentParser(prog="tools/generate_adapters.py",
                                     description="Regenerate or drift-check RAD runtime adapters.")
    parser.add_argument("--all", action="store_true", help="regenerate all expected adapter files")
    parser.add_argument("--check", action="store_true", help="read-only drift check (default mode when --all is absent)")
    parser.add_argument("--json", action="store_true", help="emit a machine-readable JSON report")
    parser.add_argument("--root", default=None, help="workspace root (default: repo root)")
    parser.add_argument("--manifest", default=None, help="path to manifest (default: <root>/.rad/manifest.json)")
    parser.add_argument("--quiet", action="store_true", help="suppress non-essential output")
    args = parser.parse_args(argv)

    root = Path(args.root) if args.root else Path(__file__).resolve().parent.parent
    if not root.is_dir():
        _fail(args, "workspace root does not exist: %s" % root)
        return 2
    manifest_path = Path(args.manifest) if args.manifest else root / ".rad" / "manifest.json"

    do_write = args.all and not args.check
    unknown = []
    try:
        manifest = load_manifest(manifest_path, workspace_root=root)
        unknown = [a for a in manifest.get("generated_adapters", []) if a not in ADAPTERS]
        try:
            manifest_rel = manifest_path.resolve().relative_to(root.resolve()).as_posix()
        except ValueError:
            manifest_rel = manifest_path.as_posix()
        fp = core_fingerprint(root, manifest_rel, manifest)
        expected = expected_files(manifest, fp)
    except GeneratorError as exc:
        _fail(args, str(exc))
        return 2

    report = {"ok": False, "fingerprint": fp, "missing": [], "drifted": [], "stale": [],
              "generated": 0, "expected_files": len(expected), "adapter": "all"}
    notes = []

    if do_write:
        written = write_all(root, manifest, fp)
        report["generated"] = len(written)
        report["ok"] = True
    else:
        missing, drifted, stale, notes = check(root, manifest, fp)
        report["missing"] = missing
        report["drifted"] = drifted
        report["stale"] = stale
        report["ok"] = not (missing or drifted or stale)

    code = 0 if report["ok"] else 1
    if args.json:
        print(json.dumps(report, sort_keys=True))
        return code
    if args.quiet and report["ok"]:
        return code
    for note in notes:
        print("note: %s" % note)
    if do_write:
        print("generated %d adapter files (fingerprint=%s)" % (report["generated"], fp))
        for rel in sorted(written):
            print("  - %s" % rel)
        if unknown:
            print("skipped unknown adapters: %s" % ", ".join(unknown))
    elif report["ok"]:
        print("OK: no adapter drift (expected_files=%d, fingerprint=%s)" % (report["expected_files"], fp))
    else:
        print("DRIFT DETECTED (fingerprint=%s)" % fp)
        for label in ("missing", "drifted", "stale"):
            items = report[label]
            print("%s (%d):" % (label, len(items)))
            for rel in items:
                print("  - %s" % rel)
    return code


def _fail(args, message):
    if args.json:
        print(json.dumps({"ok": False, "error": message}, sort_keys=True))
    else:
        print("error: %s" % message, file=sys.stderr)


if __name__ == "__main__":
    sys.exit(main())